export default async (h) => {
  const phase = async () => (await h.state("quiz"))?.phase;
  h.check("accueil", await phase() === "intro" && await h.visible("[data-phase=intro]") === 1, await phase());
  h.check("infos d'accueil", (await h.text("[data-phase=intro]"))[0]?.includes("3 questions · 5 s par question"), await h.text("[data-phase=intro]"));
  await h.click("[data-start] , [data-start]");
  await h.wait(500);
  h.check("question 1 affichée", await phase() === "play" && (await h.text("[data-phase=play]"))[0]?.includes("Quel château enjambe le Cher ?"), await h.text("[data-phase=play]"));
  h.check("3 réponses visibles (pas 6)", await h.visible("[data-answer]") === 3, await h.visible("[data-answer]"));
  const left1 = (await h.state("quiz")).left; await h.wait(600);
  h.check("chrono qui défile", (await h.state("quiz")).left < left1);
  await h.click("[data-answer='1']");
  await h.wait(400);
  let s = await h.state("quiz");
  h.check("bonne réponse + bonus", s.phase === "feedback" && s.good === 1 && s.score > 100 && s.score <= 200, JSON.stringify({score: s.score, msg: s.msg}));
  h.check("explication", (await h.text("[data-phase=feedback]"))[0]?.includes("Sa galerie traverse la rivière."), await h.text("[data-phase=feedback]"));
  await h.click("[data-next]"); await h.wait(400);
  h.check("question 2 (4 réponses)", (await h.state("quiz")).i === 1 && await h.visible("[data-answer]") === 4, await h.visible("[data-answer]"));
  await h.wait(5600);
  s = await h.state("quiz");
  h.check("temps écoulé", s.phase === "feedback" && s.msg.startsWith("Temps écoulé") && s.good === 1, s.msg);
  await h.click("[data-next]"); await h.wait(400);
  await h.click("[data-answer='1']"); await h.wait(400);
  s = await h.state("quiz");
  h.check("mauvaise réponse", s.phase === "feedback" && s.msg.includes("ses jardins") && s.good === 1, s.msg);
  await h.click("[data-next]"); await h.wait(400);
  s = await h.state("quiz");
  h.check("écran final", s.phase === "end" && s.final === "1 / 3" && await h.visible("[data-phase=end]") === 1, JSON.stringify({final: s.final, verdict: s.verdict, score: s.score}));
  await h.click("[data-restart]"); await h.wait(300);
  h.check("rejouer → accueil", await phase() === "intro");
};
