/*Generated by concorde router generator*/
import { html } from "lit";
import "@supersoniks/concorde/core/components/functional/router/router";

import layout from "./layout";
import adminLayout from "./admin/layout";
import admin_slugAtelierPage from "./admin/[slug]/atelier/page";
import admin_slugEditPage from "./admin/[slug]/edit/page";
import admin_slugVersionsPage from "./admin/[slug]/versions/page";
import adminAtelierPage from "./admin/atelier/page";
import adminPage from "./admin/page";
import cloudLayout from "./cloud/layout";
import cloudPage from "./cloud/page";
import page from "./page";
import {renderPublicArtifactRoute} from "./public-artifact-route";
export const router = (basePath?:string) => {
const admin_slugAtelierDefaultLayoutRoutes = {
    "/admin/:slug/atelier": admin_slugAtelierPage
}        

const admin_slugEditDefaultLayoutRoutes = {
    "/admin/:slug/edit": admin_slugEditPage
}        

const admin_slugVersionsDefaultLayoutRoutes = {
    "/admin/:slug/versions": admin_slugVersionsPage
}        

const admin_slugDefaultLayoutRoutes = {
    "/admin/:slug/atelier(/*)": () => html`<sonic-router .basePath=${basePath} .routes=${admin_slugAtelierDefaultLayoutRoutes}></sonic-router>`,
    "/admin/:slug/edit(/*)": () => html`<sonic-router .basePath=${basePath} .routes=${admin_slugEditDefaultLayoutRoutes}></sonic-router>`,
    "/admin/:slug/versions(/*)": () => html`<sonic-router .basePath=${basePath} .routes=${admin_slugVersionsDefaultLayoutRoutes}></sonic-router>`
}        

const adminAtelierDefaultLayoutRoutes = {
    "/admin/atelier$": adminAtelierPage
}        

const adminLayoutRoutes = {
    "/admin/:slug(/*)": () => html`<sonic-router .basePath=${basePath} .routes=${admin_slugDefaultLayoutRoutes}></sonic-router>`,
    "/admin/atelier\\b": () => html`<sonic-router .basePath=${basePath} .routes=${adminAtelierDefaultLayoutRoutes}></sonic-router>`,
    "/admin$": adminPage
}        

const cloudLayoutRoutes = {
    "/cloud$": cloudPage
}        

const layoutRoutes = {
    "/$": page,
    "/admin\\b": (params?: Record<string, string>) => adminLayout(html`<sonic-router .basePath=${basePath} .routes=${adminLayoutRoutes}></sonic-router>`, params),
    "/cloud\\b": (params?: Record<string, string>) => cloudLayout(html`<sonic-router .basePath=${basePath} .routes=${cloudLayoutRoutes}></sonic-router>`, params),
    fallback: () => renderPublicArtifactRoute(),
}        
return layout(html`<sonic-router .basePath=${basePath} .routes=${layoutRoutes}></sonic-router>`)}